services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dinakar
      POSTGRES_PASSWORD: dina
      POSTGRES_DB: ea_ai
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - perplexica-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - perplexica-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  app:
    image: escapeartist-ai/app:latest
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
    environment:
      - NODE_ENV=production
      - SEARXNG_API_URL=http://searxng:8080
      - DATA_DIR=/home/EA-Agent
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      # PostgreSQL Configuration
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=dinakar
      - DB_PASSWORD=dina
      - DB_NAME=ea_ai
      # Stripe Configuration
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - STRIPE_MONTHLY_PRICE_ID=${STRIPE_MONTHLY_PRICE_ID}
      - STRIPE_YEARLY_PRICE_ID=${STRIPE_YEARLY_PRICE_ID}
      # Token Limits - FREE PLAN (GPT-4o-mini only)
      - FREE_LIMIT_GPT_4O_MINI=${FREE_LIMIT_GPT_4O_MINI:-20000}
      # Token Limits - PRO PLAN
      - PRO_LIMIT_GPT_4O_MINI=${PRO_LIMIT_GPT_4O_MINI:-2000000}
      - PRO_LIMIT_GPT_4_1=${PRO_LIMIT_GPT_4_1:-50000}
      - PRO_LIMIT_CLAUDE_SONNET_4=${PRO_LIMIT_CLAUDE_SONNET_4:-100000}
      - PRO_LIMIT_GEMINI_2_5_PRO=${PRO_LIMIT_GEMINI_2_5_PRO:-200000}
      # Legacy models limits
      - FREE_LIMIT_GPT_4O=${FREE_LIMIT_GPT_4O:-0}
      - PRO_LIMIT_GPT_4O=${PRO_LIMIT_GPT_4O:-50000}
      - FREE_LIMIT_GPT_4=${FREE_LIMIT_GPT_4:-0}
      - PRO_LIMIT_GPT_4=${PRO_LIMIT_GPT_4:-50000}
      - FREE_LIMIT_CLAUDE_OPUS_4=${FREE_LIMIT_CLAUDE_OPUS_4:-0}
      - PRO_LIMIT_CLAUDE_OPUS_4=${PRO_LIMIT_CLAUDE_OPUS_4:-50000}
      - FREE_LIMIT_CLAUDE_3_HAIKU=${FREE_LIMIT_CLAUDE_3_HAIKU:-0}
      - PRO_LIMIT_CLAUDE_3_HAIKU=${PRO_LIMIT_CLAUDE_3_HAIKU:-100000}
      - FREE_LIMIT_CLAUDE_3_SONNET=${FREE_LIMIT_CLAUDE_3_SONNET:-0}
      - PRO_LIMIT_CLAUDE_3_SONNET=${PRO_LIMIT_CLAUDE_3_SONNET:-100000}
      - FREE_LIMIT_GEMINI_PRO=${FREE_LIMIT_GEMINI_PRO:-0}
      - PRO_LIMIT_GEMINI_PRO=${PRO_LIMIT_GEMINI_PRO:-100000}
    ports:
      - 3000:3000
    networks:
      - perplexica-network
    volumes:
      - uploads:/home/EA-Agent/uploads
      - ./config.toml:/home/EA-Agent/config.toml:ro
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 6G
        reservations:
          cpus: '1'
          memory: 2G
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
      net.core.somaxconn: '2048'
      net.ipv4.tcp_max_syn_backlog: '2048'
      net.ipv4.tcp_keepalive_time: '600'
      net.ipv4.tcp_keepalive_intvl: '60'
      net.ipv4.tcp_keepalive_probes: '3'
    depends_on:
      - postgres
      - searxng
    restart: unless-stopped

networks:
  perplexica-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
      com.docker.network.bridge.enable_icc: 'true'
      com.docker.network.bridge.enable_ip_masquerade: 'true'

volumes:
  uploads:
  postgres_data:
