import MetaSearchAgent from '@/lib/search/metaSearchAgent';
import prompts from '../prompts';

export const searchHandlers: Record<string, MetaSearchAgent> = {
  webSearch: new MetaSearchAgent({
    activeEngines: [],
    queryGeneratorPrompt: prompts.webSearchRetrieverPrompt,
    responsePrompt: prompts.webSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: true,
  }),
  academicSearch: new MetaSearchAgent({
    activeEngines: ['arxiv', 'google scholar', 'pubmed'],
    queryGeneratorPrompt: prompts.academicSearchRetrieverPrompt,
    responsePrompt: prompts.academicSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0,
    searchWeb: true,
    summarizer: false,
  }),
  writingAssistant: new MetaSearchAgent({
    activeEngines: [],
    queryGeneratorPrompt: '',
    responsePrompt: prompts.writingAssistantPrompt,
    rerank: true,
    rerankThreshold: 0,
    searchWeb: false,
    summarizer: false,
  }),
  wolframAlphaSearch: new MetaSearchAgent({
    activeEngines: ['wolframalpha'],
    queryGeneratorPrompt: prompts.wolframAlphaSearchRetrieverPrompt,
    responsePrompt: prompts.wolframAlphaSearchResponsePrompt,
    rerank: false,
    rerankThreshold: 0,
    searchWeb: true,
    summarizer: false,
  }),
  youtubeSearch: new MetaSearchAgent({
    activeEngines: ['youtube'],
    queryGeneratorPrompt: prompts.youtubeSearchRetrieverPrompt,
    responsePrompt: prompts.youtubeSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
  redditSearch: new MetaSearchAgent({
    activeEngines: ['reddit'],
    queryGeneratorPrompt: prompts.redditSearchRetrieverPrompt,
    responsePrompt: prompts.redditSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
  newsSearch: new MetaSearchAgent({
    activeEngines: ['bing news', 'google news'],
    queryGeneratorPrompt: prompts.newsSearchRetrieverPrompt,
    responsePrompt: prompts.newsSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
  shoppingSearch: new MetaSearchAgent({
    activeEngines: ['amazon', 'google shopping'],
    queryGeneratorPrompt: prompts.shoppingSearchRetrieverPrompt,
    responsePrompt: prompts.shoppingSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
  medicalSearch: new MetaSearchAgent({
    activeEngines: ['pubmed', 'google scholar'],
    queryGeneratorPrompt: prompts.medicalSearchRetrieverPrompt,
    responsePrompt: prompts.medicalSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
  financeSearch: new MetaSearchAgent({
    activeEngines: ['bing', 'google'],
    queryGeneratorPrompt: prompts.financeSearchRetrieverPrompt,
    responsePrompt: prompts.financeSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
  travelSearch: new MetaSearchAgent({
    activeEngines: ['bing', 'google'],
    queryGeneratorPrompt: prompts.travelSearchRetrieverPrompt,
    responsePrompt: prompts.travelSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
  jobSearch: new MetaSearchAgent({
    activeEngines: ['bing', 'google'],
    queryGeneratorPrompt: prompts.jobSearchRetrieverPrompt,
    responsePrompt: prompts.jobSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
  legalSearch: new MetaSearchAgent({
    activeEngines: ['bing', 'google'],
    queryGeneratorPrompt: prompts.legalSearchRetrieverPrompt,
    responsePrompt: prompts.legalSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
  recipeSearch: new MetaSearchAgent({
    activeEngines: ['bing', 'google'],
    queryGeneratorPrompt: prompts.recipeSearchRetrieverPrompt,
    responsePrompt: prompts.recipeSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
  realEstateSearch: new MetaSearchAgent({
    activeEngines: ['bing', 'google'],
    queryGeneratorPrompt: prompts.realEstateSearchRetrieverPrompt,
    responsePrompt: prompts.realEstateSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
  businessAnalysis: new MetaSearchAgent({
    activeEngines: ['bing', 'google'],
    queryGeneratorPrompt: prompts.businessAnalysisRetrieverPrompt,
    responsePrompt: prompts.businessAnalysisResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
  fitnessSearch: new MetaSearchAgent({
    activeEngines: ['bing', 'google'],
    queryGeneratorPrompt: prompts.fitnessSearchRetrieverPrompt,
    responsePrompt: prompts.fitnessSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
  designInspiration: new MetaSearchAgent({
    activeEngines: ['bing', 'google'],
    queryGeneratorPrompt: prompts.designInspirationRetrieverPrompt,
    responsePrompt: prompts.designInspirationResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
  musicSearch: new MetaSearchAgent({
    activeEngines: ['bing', 'google'],
    queryGeneratorPrompt: prompts.musicSearchRetrieverPrompt,
    responsePrompt: prompts.musicSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
  gamingSearch: new MetaSearchAgent({
    activeEngines: ['bing', 'google'],
    queryGeneratorPrompt: prompts.gamingSearchRetrieverPrompt,
    responsePrompt: prompts.gamingSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
  educationSearch: new MetaSearchAgent({
    activeEngines: ['bing', 'google'],
    queryGeneratorPrompt: prompts.educationSearchRetrieverPrompt,
    responsePrompt: prompts.educationSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
  codingSearch: new MetaSearchAgent({
    activeEngines: ['bing', 'google'],
    queryGeneratorPrompt: prompts.codingSearchRetrieverPrompt,
    responsePrompt: prompts.codingSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
  languageSearch: new MetaSearchAgent({
    activeEngines: ['bing', 'google'],
    queryGeneratorPrompt: prompts.languageSearchRetrieverPrompt,
    responsePrompt: prompts.languageSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
  dataAnalysis: new MetaSearchAgent({
    activeEngines: ['bing', 'google'],
    queryGeneratorPrompt: prompts.dataAnalysisRetrieverPrompt,
    responsePrompt: prompts.dataAnalysisResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
  }),
};
